### PR TITLE
feat: Angular 18 Support

### PR DESCRIPTION
**Pull request by KristofGilis**
# What is this PR about

Add support for Angular 18

## PR Checklist

Please check if your PR fulfils the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] The commit message follows [the guidelines](./contributing.md#commit)

### CODE REVIEW

**Comment by trav164** [comment]
@udayvunnam Can we get this reviewed please?

**Comment by AhsanAyaz** [comment]
@udayvunnam  any plans to review this soon?

**Comment by SalvoDiblasi** [comment]
@udayvunnam pls can you accept this pr? Thank you so much

**Comment by jamielegg** [comment]
@udayvunnam This would be really useful, would appreciate a review :)

**Comment by udayvunnam** [comment]
done! some more issues are fixed with [PR](https://github.com/udayvunnam/xng-breadcrumb/pull/205).

Please upgrade to latest xng-breadcrumb version. https://udayvunnam.github.io/xng-breadcrumb/#/angular-version-compatibility

**Pull request merged**
