### PR TITLE
feat: make routeSnapshot data available in breadcrumb function

### PR DESCRIPTION
**Pull request by udayvunnam**
# What is this PR about

- make routeSnapshot data available in breadcrumb function
- use NavigationEnd instead of GuardCheck

## PR Checklist

Please check if your PR fulfils the following requirements:

- [x] The commit message follows [the guidelines](./contributing.md#commit)
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### CODE REVIEW

**Comment by luizagabriela** [comment]
Hello!

There are still plans to merge the this PR to make activatedRouteSnapshot data available in breadcrumb function?

**Comment by udayvunnam** [comment]
Yes, @luizagabriela

**Comment by luizagabriela** [comment]
I'm glad to hear that this functionality will be integrated, it will help us.
Do you know when the changes will be merge?

**Comment by RalucaCorb** [comment]
Hello
Do you know when this PR will be merged?

**Comment by udayvunnam** [comment]
I will try to get this fixed and merged over the weekend

**Comment by RalucaCorb** [comment]
Great! Thanks.

**Comment by luizagabriela** [comment]
Hi! Do you know when this PR will be merged?

**Comment by MiroslavGrozdanovski** [comment]
Hi @udayvunnam, any plans to merge this soon? Thanks!

**Pull request closed without merging**
